-- 013_legal_consents.sql
-- Legal document versioning, releases, and append-only user acceptance history.

create table public.legal_documents (
  id bigint generated by default as identity primary key,
  document_type text not null check (document_type in ('terms', 'privacy')),
  version text not null,
  effective_at timestamptz not null,
  path text not null,
  created_at timestamptz not null default now(),
  unique (document_type, version)
);

create table public.legal_releases (
  id bigint generated by default as identity primary key,
  release_no bigint generated by default as identity unique not null,
  terms_document_id bigint not null references public.legal_documents(id) on delete restrict,
  privacy_document_id bigint not null references public.legal_documents(id) on delete restrict,
  requires_reconsent boolean not null default false,
  effective_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (terms_document_id, privacy_document_id)
);

create table public.user_legal_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  legal_release_id bigint not null references public.legal_releases(id) on delete restrict,
  accepted_at timestamptz not null default now(),
  unique (user_id, legal_release_id)
);

create index user_legal_acceptances_user_id_idx
  on public.user_legal_acceptances(user_id);

alter table public.legal_documents enable row level security;
alter table public.legal_releases enable row level security;
alter table public.user_legal_acceptances enable row level security;

create policy "legal_documents are readable"
  on public.legal_documents for select
  to anon, authenticated
  using (true);

create policy "legal_releases are readable"
  on public.legal_releases for select
  to anon, authenticated
  using (true);

create policy "users can read own legal acceptances"
  on public.user_legal_acceptances for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- No direct INSERT/UPDATE/DELETE policy is created for acceptance history.
-- Acceptance is recorded only through the authenticated RPC below.

create or replace function public.record_current_legal_acceptance()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_release_id bigint;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  select lr.id
    into v_release_id
    from public.legal_releases lr
   where lr.effective_at <= now()
   order by lr.release_no desc
   limit 1;

  if v_release_id is null then
    raise exception 'No active legal release';
  end if;

  insert into public.user_legal_acceptances (
    user_id,
    legal_release_id
  )
  values (
    v_user_id,
    v_release_id
  )
  on conflict (user_id, legal_release_id) do nothing;

  return v_release_id;
end;
$$;

create or replace function public.get_legal_acceptance_status()
returns table (
  current_release_id bigint,
  has_any_acceptance boolean,
  requires_acceptance boolean,
  reason text
)
language sql
stable
security definer
set search_path = ''
as $$
  with current_release as (
    select lr.id, lr.release_no
      from public.legal_releases lr
     where lr.effective_at <= now()
     order by lr.release_no desc
     limit 1
  ),
  latest_acceptance as (
    select lr.release_no
      from public.user_legal_acceptances ula
      join public.legal_releases lr on lr.id = ula.legal_release_id
     where ula.user_id = auth.uid()
     order by lr.release_no desc
     limit 1
  ),
  pending_required_release as (
    select 1
      from public.legal_releases lr
      cross join current_release cr
     where lr.release_no <= cr.release_no
       and lr.requires_reconsent = true
       and lr.release_no > coalesce(
         (select la.release_no from latest_acceptance la),
         0
       )
     limit 1
  )
  select
    cr.id,
    exists (
      select 1
        from public.user_legal_acceptances ula
       where ula.user_id = auth.uid()
    ),
    case
      when auth.uid() is null then true
      when not exists (
        select 1
          from public.user_legal_acceptances ula
         where ula.user_id = auth.uid()
      ) then true
      else exists (select 1 from pending_required_release)
    end,
    case
      when auth.uid() is null then 'authentication_required'
      when not exists (
        select 1
          from public.user_legal_acceptances ula
         where ula.user_id = auth.uid()
      ) then 'no_acceptance'
      when exists (select 1 from pending_required_release) then 'legal_update'
      else 'accepted'
    end
  from current_release cr;
$$;

revoke all on function public.record_current_legal_acceptance() from public;
revoke all on function public.get_legal_acceptance_status() from public;
grant execute on function public.record_current_legal_acceptance() to authenticated;
grant execute on function public.get_legal_acceptance_status() to authenticated;

grant select on public.legal_documents to anon, authenticated;
grant select on public.legal_releases to anon, authenticated;
grant select on public.user_legal_acceptances to authenticated;

-- Initial published documents and release.
insert into public.legal_documents (
  document_type,
  version,
  effective_at,
  path
)
values
  ('terms', '2026-08-29', '2026-08-29 00:00:00+09', '/terms'),
  ('privacy', '2026-08-29', '2026-08-29 00:00:00+09', '/privacy');

insert into public.legal_releases (
  terms_document_id,
  privacy_document_id,
  requires_reconsent,
  effective_at
)
select
  t.id,
  p.id,
  true,
  '2026-08-29 00:00:00+09'
from public.legal_documents t
cross join public.legal_documents p
where t.document_type = 'terms'
  and t.version = '2026-08-29'
  and p.document_type = 'privacy'
  and p.version = '2026-08-29';
